### ISSUE TITLE
Installation failed: Visual Studio required

### ISSUE THREAD

**Issue by Vort** [ortexx/museria-global#3]
If Python requirement is "ok", this is too much:
```
c:\museria>npm i

> diskusage@1.1.3 install c:\museria\node_modules\diskusage
> node-gyp rebuild


c:\museria\node_modules\diskusage>if not defined npm_config_node_gyp (node "C:\n
odejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\nodejs\node_modules\npm\node_m
odules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-
visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-
visualstudio.js:70:14
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-
visualstudio.js:372:16
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.
js:54:7
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.
js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\museria\node_modules\diskusage
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is install
ed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is instal
led. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vort\AppData\Roaming\npm-cache\_logs\2020-04-01T11_21_34_9
71Z-debug.log
```
Why not just write project in C++ then :/

**Comment by ortexx** [comment]
I assume you didn't work with nodejs before? All these dependencies are required for [node_gyp](https://github.com/nodejs/node-gyp) tool. This library is common used in nodejs projects to add [c++ addons](https://nodejs.org/api/addons.html). If you follow the links above you can find more information. You just need to install node_gyp.

**Comment by Vort** [comment]
> I assume you didn't work with nodejs before?

I used it only on "Hello, world!" level.

But anyway, such dependencies should be mentioned in documentation.
Since user should know what amount of software he need to install.

`npm install --global --production windows-build-tools`, which is mentioned at your link, after 20 minutes of waiting still shows "---------- Visual Studio Build Tools ---------- / Still waiting for installer log file..."
Looks like people nowadays can't think that command can exit with error, which is happened with that `vs_BuildTools.exe`:
```
[4/1/2020, 14:54:3] === Logging started: 2020/04/01 14:54:03 ===
[4/1/2020, 14:54:3] Executable: C:\Users\Vort\.windows-build-tools\vs_BuildTools.exe v15.5.27130.2027
[4/1/2020, 14:54:3] --- logging level: standard ---
[4/1/2020, 14:54:3] Error 0x80044000: Prerequisite required on system.
[4/1/2020, 14:54:3] The entire Box execution exiting with result code: 0x80044000
[4/1/2020, 14:54:3] Launched extracted application exiting with result code: 0x0
[4/1/2020, 14:54:3] === Logging stopped: 2020/04/01 14:54:03 ===
```

Not sure what I want to do next with it.
Maybe you will try to make full installation with Windows 7 on your own?

**Comment by ortexx** [comment]
I tried. I agree, it is no so clear for everyone. But it is expected if you work with **nodejs** and **windows** together :)

Thousands of libraries use node_gyp. If you work with nodejs sooner or later you will have to install it. 

I'm gonna add this requirement in docs.

**Comment by Vort** [comment]
Just in case someone is interested what is that magic 0x80044000 prerequisite:
![dnet](https://user-images.githubusercontent.com/1242858/78146033-4acb8b00-743a-11ea-80b4-14e15563489e.png)
